### ISSUE TITLE
Add README and a LICENSE

### ISSUE THREAD

**Issue by RemiLehe** [RemiLehe/openPMD-example-datasets#2]

**Comment by ax3l** [comment]
For example data sets I would propose the [CC0 License](https://github.com/ComputationalRadiationPhysics/openPMD/blob/127b4c1e66536e4bad4a07ce2bf3d82317e9fcac/LICENSE) or the [CC-BY License](https://raw.githubusercontent.com/ComputationalRadiationPhysics/openPMD/b204ea4680af8ac4a70ef7f2eda9c8572154dda1/LICENSE?token=ABSmKvfAdHiY0hHVoCAMsrKLcox-w_Ziks5WF2iXwA%3D%3D).

In case you a curious, [this page explains the various CC-BY licenses](http://foter.com/blog/how-to-attribute-creative-commons-photos/), [this is CC0](https://creativecommons.org/publicdomain/) (public domain) and here are [best practices](https://wiki.creativecommons.org/wiki/Best_practices_for_attribution) when quoting.

**Comment by RemiLehe** [comment]
I agree with the CC0 License. Let's us this one.

**Comment by RemiLehe** [comment]
In the README, one should add that git lfs is necessary for cloning the repo.
