### ISSUE TITLE
basePath is resolved in all examples

### ISSUE THREAD

**Issue by PrometheusPi** [RemiLehe/openPMD-example-datasets#5]
In all examples the attribute `basePath` is set to `"/data/{}/"` with `{}` being the iteration.  
Following the [standard](https://github.com/openPMD/openPMD-standard/blob/latest/STANDARD.md#hierarchy-of-the-data-file), `basePath` should be `/data/%T/` instead. 

see [openPMD/openPMD-validator/#11](https://github.com/openPMD/openPMD-validator/pull/11)

**Comment by ax3l** [comment]
@RemiLehe how did this pass the validator? ;)

can you pls update the examples? :)

**Comment by ax3l** [comment]
ah not checked by the validator! good catch @PrometheusPi https://github.com/openPMD/openPMD-validator/pull/11

**Comment by ax3l** [comment]
fixed with #6
